### ISSUE TITLE
Agora audit error in windows 8

### ISSUE THREAD

**Issue by lucascervera** [agoravoting/agora-airgap#1]
When I try to audit a ballot I receive the following message:

status: error

> election data downloadedcurl_easy_perform() failed:SSL peer certificate or SSH remote key was not OK

**Comment by edulix** [comment]
@lucascervera you need to provide more information, for example in this case it would be invaluable if you provide the auditable-ballot that is failing

**Comment by lucascervera** [comment]
the url:

https://pre.agoravoting.com/#/election/20/vote/271cf212cae409ab22ee7d0a58bfd436ba5965abe3b676843d8c4e41a55ce1ba/c623b751b20f31e3fa5c2b9ebb15:AuthEvent:20:vote:1423473464

the ballot:

{"ballot_hash":"894c499ef2387b6aaf8c9fe0e73139478887937cd4c8d8220a2f2294955a6e2b","choices":[{"alpha":"48034091982511799608663590358197513398430673572638019231960106998534588161452334921057119600580520634378013755732658018608165353081275569694143554143394331202721062535028232287493797690059755317536447612765714197109247763574197173532453542238723544816744318297260815684823951069550855711643170941555974814757408271496628813776934442963678357234149284047479263790747871762735468792831878164020566398488806950110670214965747492221681289151600841034435444538609462318777512792661996243459298682369246405723325949633615336506737711320094234635523644065408944880075057255932277228109040646599063865046899676145268285835417","beta":"49564532617172276149487481619937312055445355460020870816252399954840092056782327587666142307701750953733575027649340871770986052012379988601726614269583772077471722463316184337495922598950422403876078835072911056936240335836390178676163982303669275265844818831724913858288598047692137969020105847854955111573824953734481566796941138584307810450484508766239626247500529304916592992169134825204514847576709239976285421497613618399684169254390597572895317387101407369832770728122236283165589581889095296836124631563472948802611185960459132686133399942406856265413229156099615922159642684798968742219659331428747282572611","plaintext":"0305","randomness":"6022335309129521725774365611897525201803984387562547424786922663479443264274848868541515662391432152406534893262089046500275847019443487520094303689813484009073806558986777600805222588953261680335262760932097791511384772238867153627744369048006077866909809620976773152523668457434703206758209459714139779052123900066941846366654399375158619291373870028020732631891390687886526740980475281540607369291831102111092223421944212386376135399706900941181304305851294648273107674274917771489128072086544188997893114292291530631172915489551905131472536353872469693395890284588855374607928363697057041636253735231814188304420"},{"alpha":"17450253535139366787034224973311321443409583006900529760375300729221257414802762989302951380965437987604076598243678734033095244385405058446283004267212969297336171213595092838597089957230003959896311701848597635706764457297588299022228165620568720920787817603083170787185994910883651687714749032697866590018862890714178231719237887377636542781006261610922082780355863396770043055394387052584406512896340473442673688113060588650686478044014577442562959703912908986040033652980434585522835541967169043812212499631499270308287225282679041871441339803126057940494304670673852309405392377950514621419080110388666336966977","beta":"33656175055347146770417194467136642884386930030816487036185789889664320477666788057581502401674662883602672908879576187471543861952009997778672416155874993367507251668929940885367294359133550727757650001223581292583716103973400065755906990007953399642173028269411303515891417644392433650023188723342949578470654727973505082694126614836514615733219307983597501598623283344066504394069725672111146164339151954397947005077135164451541843304252695621950704452349436491102121384783878747151888942595116309094722051070728545377495265440412381743622444751093765072033190263023453783064827741626038122540790676048223444875876","plaintext":"0504","randomness":"1657803572854848234767078680822017570883693571245309626934297897579186650103452206967809155994206985933444061859371452748982433980719836257073982261999824422858930345230313420701004232665611149809793975888214564660605127172684937861810534903287348209898659301764365328731528624936213790257909641402922113914678011819597903653148646216068411005125817239953807450536315822345855423295730413042412785136923616944861933913714326851470677204676812501157993180354155746831684892956615953927887304310527021222976696993735952446170393529459078471757456430685934071937603277606792188757273148599042400685414725680534651222037"}],"election_url":"https://pre.agoravoting.com/elections/api/election/20","issue_date":"09/02/2015","proofs":[{"challenge":"52522662839320333239643263770871703702622453923467312842841066537732599733649","commitment":"36228443768964177117313791263547028155881122956615482565594611182008797870370819002282378178306746962556690821040599996522150314393903891688781669788005283634205185533781638745252729362220740952292655716635353584556731249457020617412451815909550809701896911354443421572161611451004974608287932571024691072947603870415831377654750782232647479350275676177164758994097714864866710774986010098782757045394444966306505058631141837121527503054542237875066522231142819000189479860278585099450751335404697036475073206557603441847611218907571664429663516265089871947197764895640091270873389257940820692405648764630355188064332","response":"8590943544337840623038448347437367674202387210962587518045830354593271110410322944529345893511877909731003982628215356744595963202497744878521344833202390292961799099813928849584285404030814763508019905208547590914108908519507368165451759676122265137083942405069021880790913610965563393383915620423201190888391456551771433466195187061469558460694798061594076056031118819180227788910488479232800431371715867880737861635927453062747622217330426403044405613618200199952780731161040007850257209417896836592093887162685835210872027489713483716644280763930874403731384810907747730503748772120843752839852887352520951304358"},{"challenge":"114306725771361745140649975944698477372483403959766535242506129476382228428416","commitment":"39599822689924201133619389071255336019026752185213928917157948383737597108563539214608148841934143694125043145899679257425811465379462396965156470880009377542371963550776022471317575662729018038870616160622490918214905019704382857961684541575290965968303957627942853184270297706184772740123606746747466439514835625219735646685306898244175422720389531756042605891007284702626262196246037084720287180791078339272988547335800842610518632462006234921369311222027376646517878244684700812349113233207647408096627878757094790969333950012710638437640199396518438403707329746272299532102174856579273391874399532998787638318694","response":"8369268932116490782060477768415628742303036410459639391132127773075338556853591322345217184284207272285467813392867161959549839059442861748058282853946764101388466286463906654014105781482299508147270766586210958108129159905062546745941654724839963597129910852277458428679045689344652472268543398964982313689282403798070922675919700129412067084534883301579999297693275535433799058152392460062603456313797398057936281453279102457701307268743273677705848546060812698040059196208244365022448599523285444328958275729876809155540806150958708818148393978693294084853273136804510473276550838853908370705142874648217012721809"}]}

**Comment by edulix** [comment]
The reason I think is very simple:  pre environment is using a self-signed TLS certificate. This issue only happens in pre because it's not a production environment, and the best solution is probably to change the certificate in pre, instead of changing anything here. Closing the issue.
